packages:
  - apps/*
  - services/*
  - packages/*
  - tests/*

allowBuilds:
  bufferutil: set this to true or false
  esbuild: true
  keccak: set this to true or false
  sharp: false
  utf-8-validate: set this to true or false

overrides:
  "brace-expansion@>=4.0.0 <5.0.9": 5.0.9
  "nanoid@<3.3.17": 3.3.17

minimumReleaseAgeExclude:
  - viem@2.55.5
